"""
Central path configuration.
Use environment variables to override paths, otherwise fall back to project-relative defaults.
"""
from os import getenv
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

def _p(name: str, default: Path):
    value = getenv(name)
    return Path(value).expanduser() if value else default

# ── Output directory (all figures and CSV results are saved here) ─────────────
OUT_DIR = _p("HCC_OUT_DIR", REPO_ROOT / "reports")

# ── TCGA-LIHC RNA-seq (GDC download, NAS) ────────────────────────────────────
GDC_DIR = _p("HCC_GDC_DIR", REPO_ROOT / "data" / "gdc" / "gdc_downloads")
GDC_MANIFEST = _p("HCC_GDC_MANIFEST", GDC_DIR / "gdc_manifest.txt")
TPM_MATRIX = _p("HCC_TPM_MATRIX", REPO_ROOT / "tmp" / "tcga_lihc_tpm_matrix.tsv.gz")

# ── External 106-patient TCGA-LIHC cohort (workstation) ──────────────────────
EXT_CLINICAL_CSV = _p("HCC_EXT_CLINICAL_CSV", REPO_ROOT / "data" / "external" / "tcga_data_formatted_final.csv")
SVS_INDEX_CSV = _p("HCC_SVS_INDEX_CSV", REPO_ROOT / "data" / "external" / "hcc_svs_files.csv")
SVS_BASE_DIR = _p("HCC_SVS_BASE_DIR", REPO_ROOT / "data" / "external" / "tcga_svs")

# ── WSI model outputs (ABMIL / CTransPath) ───────────────────────────────────
FINAL_RISK_TABLE = _p("HCC_FINAL_RISK_TABLE", OUT_DIR / "final_risk_table.csv")
OOF_PREDS_CSV = _p("HCC_OOF_PREDS_CSV", OUT_DIR / "oof_preds.csv")
EMBEDDINGS_DIR = _p("HCC_EMBEDDINGS_DIR", REPO_ROOT / "embeddings" / "ctranspath")
PATIENT_INDEX_CSV = _p("HCC_PATIENT_INDEX_CSV", REPO_ROOT / "data" / "index" / "patient_index.csv")
MODEL_DIR = _p("HCC_MODEL_DIR", REPO_ROOT / "models" / "mil_cox" / "abmil_resnet50_seed20260104")

# ── MRI radiomics (internal 106-patient cohort) ───────────────────────────────
MRI_DIR = _p("HCC_MRI_DIR", REPO_ROOT / "data" / "mri")
MRI_OS_CSV = _p("HCC_MRI_OS_CSV", REPO_ROOT / "data" / "mri" / "clinial_os.csv")
MRI_FEATURES_CSV = OUT_DIR / "mri_arterial_radiomics.csv"

# ── Intermediate files (generated by step2) ───────────────────────────────────
RISK_COHORT_CSV = _p("HCC_RISK_COHORT_CSV", REPO_ROOT / "tmp" / "tcga106_complete.csv")
DEG_RESULTS_CSV = OUT_DIR / "deg_results.csv"
GSEA_RESULTS_CSV = OUT_DIR / "gsea_results.csv"
